# Generated by Django 5.0.1 on 2026-01-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
